src/magic_auth/urls.py
from django.urls import path
from django.contrib.auth.views import LogoutView

from magic_auth import views

app_name = 'magic_auth'


urlpatterns = [
    path('', views.MagicUserSignUp.as_view(), name='sign_up'),
    path('sign_up_success', views.SignUpSuccessView.as_view(), name='sign_up_success'),
    path('page_for_authenticated', views.PageForAuthenticatedUsers.as_view(), name='page_for_auth_index'),
    path('logout', LogoutView.as_view(), name='logout'),
    path('<str:token>', views.magic_user_sign_in, name='sign_in'),
]

src/server/urls.py
from django.contrib import admin
from django.urls import path, include
from django.views.generic.base import RedirectView

urlpatterns = [
    path('', RedirectView.as_view(pattern_name='magic_auth:sign_up')),
    path('admin/', admin.site.urls),
    path('auth/', include('magic_auth.urls')),
]

src/magic_auth/models.py
from django.db import models
from django.contrib.auth.models import AbstractUser
from django.utils.translation import gettext_lazy as _


class MagicUser(AbstractUser):
    USERNAME_FIELD = 'email'
    REQUIRED_FIELDS = ['username']

    password = models.CharField(max_length=64, default='securepassword123')
    email = models.EmailField(unique=True, error_messages={'unique': 'User with specified email exists.'})
    auth_token = models.CharField(max_length=64, unique=True)
    logins = models.ManyToManyField('magic_auth.LoginActivity')
    has_access = models.BooleanField(default=True)

    class Meta:
        verbose_name = _('Magic user')
        verbose_name_plural = _('Magic users')


class LoginActivity(models.Model):
    at = models.DateTimeField(auto_now_add=True)

src/magic_auth/forms.py
from django.contrib.auth import get_user_model
from django import forms


class MagicUserSignUpForm(forms.ModelForm):

    def save(self, commit=True):
        self.instance.username = self.instance.email.split('@')[0]
        return super().save(commit)

    class Meta:
        model = get_user_model()
        fields = ('email',)

src/magic_auth/views.py
from django.shortcuts import HttpResponse, redirect
from django.urls import reverse_lazy
from django.views.generic.edit import CreateView
from django.views.generic.base import TemplateView
from django.contrib.auth import authenticate, login
from django.contrib.auth.mixins import LoginRequiredMixin
from django.core.mail import send_mail
from django.contrib.sites.shortcuts import get_current_site

from magic_auth.forms import MagicUserSignUpForm


class MagicUserSignUp(CreateView):
    template_name = 'sign_up.html'
    form_class = MagicUserSignUpForm
    success_url = reverse_lazy('magic_auth:sign_up_success')

    def form_valid(self, form):
        return_value = super().form_valid(form)
        current_site = get_current_site(self.request)
        message = \
            f'''
            Hi, there!\n
            Here is your authentication link:
            http://{current_site}/auth/{self.object.auth_token}\n
            Do not lose!
            '''
        send_mail(
            'Site with a magic authentication',
            message,
            f'noreply@{current_site}',
            (self.object.email,)
        )
        return return_value


class SignUpSuccessView(TemplateView):
    template_name = 'sign_up_success.html'


def magic_user_sign_in(request, token):
    user = authenticate(request, token=token)
    if user and user.has_access:
        login(request, user)
        user.logins.create()
        user.save()
        user.refresh_from_db()
        return redirect(reverse_lazy('magic_auth:page_for_auth_index'))
    else:
        return HttpResponse('<h1>Invalid auth token.</h1>')


class PageForAuthenticatedUsers(LoginRequiredMixin, TemplateView):
    template_name = 'authenticated_index.html'
    login_url = reverse_lazy('magic_auth:sign_up')

    def get_context_data(self, **kwargs):
        context_data = super().get_context_data(**kwargs)
        context_data['login_count'] = self.request.user.logins.count()
        return context_data

src/magic_auth/templates/authenticated_index.html
<!doctype html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Hello</title>
</head>
<body>
    <h1>Welcome, authenticated user.</h1>
    <h2>You have signed in {{ login_count }} time.</h2>
    <h2>Your email: {{ user.email }}</h2>
    <h3><a href ={% url 'magic_auth:logout' %}>LogOut</a></h3>
</body>
</html>

src/magic_auth/templates/page_for_authenticated.html
<!doctype html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Auth page</title>
</head>
<body>
    <h1>Welcome, authenticated user.</h1>
    <h2>You have visited this page {{ user.login_count }} times.</h2>
    <h2>Your email: {{ user.email }}</h2>
</body>
</html>

src/magic_auth/templates/sign_up.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Sign Up</title>
</head>
<body>
    <form method="POST">
        {% csrf_token %}
        {{ form.as_p }}
        <button type="submit">Sign Up</button>
    </form>
</body>
</html>

src/magic_auth/templates/sign_up_success.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Success</title>
</head>
<body>
    <h2>The mail with auth link was sent to your email.</h2>
</body>
</html>